services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    command: npm run start:dev
    environment:
      - PORT=8080
      - DATABASE_NAME=classroom
      - DATABASE_USER=root
      - DATABASE_PASS=root
      - DATABASE_URI=mongodb://database:27017
      - ELASTICSEARCH_NODE=http://esOne:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - '8080:8080'
    depends_on:
      - database
      - esOne
      - redis
    links:
      - database
      - esOne
      - redis
    volumes:
      - ./src:/app/src
    networks:
      - elastic
    
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: classroom
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - elastic

  esOne:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: esOne
    environment:
      - node.name=esOne
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTICSEARCH_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esData01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
    env_file:
      - .env.development
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - elastic

volumes:
  esData01:
  database:
  redis:

networks: 
  elastic:
    driver: bridge
