name: CI

on:
  push:
    branches-ignore:
      - 'main'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run build
      run: npm run build

    - name: Run tests
      run: npm test

  create_pull_request:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
        base: 'dev'
        title: 'Automated PR from CI'
        commit-message: 'Automated PR from CI'
        labels: 'automerge'

  automerge:
    needs: create_pull_request
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Automerge
      uses: pascalgn/automerge-action@v1
      env:
        GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN_GITHUB }}"
        MERGE_LABELS: 'automerge,!work in progress'
        MERGE_METHOD: 'squash'
        MERGE_COMMIT_MESSAGE: 'Automated merge from CI'
        MERGE_FORKS: 'false'
        UPDATE_LABELS: 'automerge'